### PR TITLE
feat: basic image resizing url transformation

### PR DESCRIPTION
**Pull request by sajuthankappan**

### CODE REVIEW

**Review by EstebanBorai — APPROVED** [review]
Thanks so much @sajuthankappan!

**Comment by EstebanBorai** [comment]
@sajuthankappan can you please make sure CI passes? Looks like we have some clippy/fmt issues.

Other than that looks good overall.

**Comment by sajuthankappan** [comment]
> 

Yes, Will look into the CI issues..

**Comment by sajuthankappan** [comment]
> @sajuthankappan can you please make sure CI passes? Looks like we have some clippy/fmt issues.
> 
> Other than that looks good overall.

I think I fixed the clippy issue. Yet to look at the fmt issue.

**Comment by sajuthankappan** [comment]
> > @sajuthankappan can you please make sure CI passes? Looks like we have some clippy/fmt issues.
> > Other than that looks good overall.
> 
> I think I fixed the clippy issue. Yet to look at the fmt issue.

I think all CI issues are fixed now. Atleast, it seems ot be running fine in my forked repo. Please check now..

**Review by EstebanBorai — APPROVED** [review]

**Pull request merged**
